apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parla-ingress
  namespace: parla-dental
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: parladental.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: parla-frontend-service
                port:
                  number: 80
