apiVersion: v1
kind: Secret
metadata:
  name: parla-postgres-secret
  namespace: parla-dental
type: Opaque
stringData:
  POSTGRES_DB: "parla_dental"
  POSTGRES_USER: "REPLACE_DB_USER"
  POSTGRES_PASSWORD: "REPLACE_DB_PASSWORD"
